package com.FATCA.API.controllers.adminAPI;

import com.FATCA.API.converter.XmlFromXsdGen;
import com.FATCA.API.fileStorage.FileInfo;
import com.FATCA.API.fileStorage.FilesStorageService;
import com.FATCA.API.fileStorage.FilesStorageServiceImpl;
import com.FATCA.API.fileStorage.ResponseMessage;
import lombok.Data;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.servlet.mvc.method.annotation.MvcUriComponentsBuilder;

import org.springframework.core.io.Resource;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

@RestController
@RequiredArgsConstructor
@RequestMapping(path="api/v1/admin")
@Slf4j
//TODO: finish the unfinished controllers
public class AdminController {
    /*
    * The admin controller contains some endpoints:
    * 1-upload the schemas (.xsd files)
    * 2-get the xml template generated by the schemas
    * 3-upload the configured template so the users can fill it with data
    * 4-get the list of all the files in the storage
    */
    @Autowired
    FilesStorageService storageService;
    //this controller allows the user to get the template
    @GetMapping(path = "/getTemplate",produces = { "application/xml", "text/xml" }, consumes = MediaType.ALL_VALUE)
    public ResponseEntity<?> getTemplate( templateForm form) throws ParserConfigurationException, TransformerException, IOException {
        String schema = storageService.load(form.getXsdName(), "xsd").getFile().toString();
        String result = XmlFromXsdGen.generateXml(schema, form.getLocalPart(), new String[]{"ftc", "sfa"});
        HttpHeaders headers = new HttpHeaders();
        return new ResponseEntity<>(result, headers, HttpStatus.CREATED);
    }

    @PostMapping("/uploadFile")
    public ResponseEntity<?> uploadFile(@RequestParam("file") MultipartFile file, String type, boolean isMain) {
        String message = "";
             try {
                 if (Objects.equals(type, "xsd")&& isMain){
                     storageService.insert("uploads/main.txt", file.getOriginalFilename());
                 }
                 storageService.save(file, type);
                 message = "Uploaded the file successfully: " + file.getOriginalFilename();
                 return ResponseEntity.status(HttpStatus.OK).body(new ResponseMessage(message));
             } catch (Exception e) {
                 message = "Could not upload the file: " + file.getOriginalFilename() + "!";
                 return ResponseEntity.status(HttpStatus.EXPECTATION_FAILED).body(new ResponseMessage(message));
             }
    }
    @GetMapping("/files")
    public ResponseEntity<List<FileInfo>> getListFiles() {
        List<FileInfo> fileInfos = storageService.loadAll().map(path -> {
            String filename = path.getFileName().toString();
            String url = MvcUriComponentsBuilder
                    .fromMethodName(AdminController.class, "getFile", path.getFileName().toString(), "").build().toString();
            return new FileInfo(filename, url);
        }).collect(Collectors.toList());
        return ResponseEntity.status(HttpStatus.OK).body(fileInfos);
    }
//    @GetMapping("/files/{filename:.+}")
//    @ResponseBody
//    public ResponseEntity<?> getFile(@PathVariable String filename) {
//        String file = storageService.load(filename, "");
//        return ResponseEntity.ok()
//                .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + file + "\"").body(file);
//    }
    @GetMapping("/templates")
    @ResponseBody
    public ResponseEntity<?> getTemplates() throws Exception {
        List<FileInfo> fileInfos = storageService.getTemplate().map(path -> {
            String filename = path.getFileName().toString();
            String url = MvcUriComponentsBuilder
                    .fromMethodName(AdminController.class, "getFile", path.getFileName().toString(), "template").build().toString();
            return new FileInfo(filename, url);
        }).collect(Collectors.toList());
        return ResponseEntity.status(HttpStatus.OK).body(fileInfos);
    }
    @GetMapping("/xsdfiles")
    @ResponseBody
    public ResponseEntity<?>getXsdFiles(){
        List<FileInfo> fileInfos = storageService.getXSDFiles().map(path -> {
            String filename = path.getFileName().toString();
            String url = MvcUriComponentsBuilder
                    .fromMethodName(AdminController.class, "getFile", path.getFileName().toString(), "xsd").build().toString();
            return new FileInfo(filename, url);
        }).collect(Collectors.toList());
        return ResponseEntity.status(HttpStatus.OK).body(fileInfos);
    }
    @GetMapping("/files/{filename:.+}/{path:.+}")
    @ResponseBody
    public ResponseEntity<Resource> getFile(@PathVariable String filename, @PathVariable String path) {
        Resource file = storageService.load(filename, path);
        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + file.getFilename() + "\"").body(file);
    }

}
@Data
class templateForm{
    private String localPart;
    private String xsdName;
}

//@Data
//class filesForm{
//    private String name;
//    private String url;
//}